#!/usr/bin/env bash

# Upload OTF and TTF instances and features from Glyphs

# locate Glyphs’ Temp folder
GlyphsTempFolder="/Users/davidbrezina/Library/Application Support/Glyphs/Temp"
translateWeightClass=( "Light:300" "Regular:400" ":400" "Medium:500" "Semibold:600" "Bold:700")


# delete old UFO instances
for family in "Rasa"
do
	cd "$family"
	shopt -s nullglob
	for i in */
	do
		UFO=$i"font.ufo"
		TTF=$i"font.ttf"
		OTF=$i"font.otf"
		if [[ -d $UFO ]]
		then
			echo "Removing old $UFO"
			rm -R $UFO
		fi
		if [[ -f $TTF ]]
		then
			echo "Removing old $TTF"
			rm $TTF
		fi
		if [[ -f $OTF ]]
		then
			echo "Removing old $OTF"
			rm $OTF
		fi
	done
	cd ..
done

# generate new UFOs
makeInstancesUFO -d Rasa.designspace -n

# generate feature files for UFO
for family in "Rasa"
do
	suf="ufo"
	cd "$family"
	for i in */
	do
		folder=`echo "$i" | sed -e "s/\([^-\.]*\)\//\1/"`
		weight=`echo "$folder" | sed -e "s/Italic//"`

		# generate mark feature for font.ufo
		echo "Generating feature files for $folder"
		cd "$folder"
		appendGroupsUFO.py -g ../../shared.groups.txt font.ufo # implant COMBINING_MARKS class
		cd ..

		# add weightClass definition files
		for weightRecord in "${translateWeightClass[@]}"
		do
   			KEY="${weightRecord%%:*}"
    		VALUE="${weightRecord##*:}"
    		if [[ $KEY == $weight ]]
    		then
				echo "Adding WeightClass file for $folder ($VALUE)"
				echo "WeightClass  $VALUE; # $folder" > $folder/WeightClass.fea
    		fi
    	done
	done
	# generate kern files
	generateAllKernFiles.py
	# generate mark feature files
	generateAllMarkFiles.py
	cd ..
done


# generate TTFs (via RoboFont)
for family in "Rasa"
do
	cd "$family"
	for i in */
	do
		cd "$i"
		echo "Generating TTF for $family/$i"
		roboGenerateFont.py font.ufo -r -c -f ttf
		cd ..
	done
	cd ..
done
